# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_post',
            field=models.BooleanField(default=False),
        ),
    ]
